model: ???
nf_outer: 10  # number of inner k-folds - number of tunings
nf_inner: 5  # number of inner k-folds - number of trainings per hyperparameter set
nt: 5000  # number of trials per tuning

features:  # path to pkl file of pre-selected features

pp: 1  # parallel processes
metric: prauc  # prauc, rocauc, acc
pruner: median  # asha, median
save_tune: 1  # must be true if pp is set
