#defaults:
#  - tune_model: ???  #choices=['torch', 'rf', 'xgb', 'svc', 'mlp', 'log'])

args:
  n_trials: 100
  dbs: ["UKE"]
  minutes: 60
  k_fold: 0
  num_splits: 3
  model_type: ???
  flat_block_size: 0
  fill_type: "pat_ema"
  opt_flat_block_size: False
  opt_augs: False
  opt_fill_type: False
  # for k-fold tune
  n_outer_folds: 3


#model_args:
#    #model_args["max_steps"] = 300